apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  JWT_KEY: "change-me-long-random-jwt-key"
  ADMIN_EMAIL: "fl2on@proton.me"
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
stringData:
  STRIPE_KEY: "sk_test_change_me"
  ENTRY_PASS_SECRET: "change-me-entry-pass-secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: hcaptcha-secret
type: Opaque
stringData:
  HCAPTCHA_SITE_KEY: "change-me-site-key"
  HCAPTCHA_SECRET_KEY: "change-me-secret-key"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  RABBITMQ_ORDERS_URL: "amqps://orders-user:change-me-orders-pass@rabbit-srv:5671/cinemax"
  RABBITMQ_TICKETS_URL: "amqps://tickets-user:change-me-tickets-pass@rabbit-srv:5671/cinemax"
  RABBITMQ_PAYMENTS_URL: "amqps://payments-user:change-me-payments-pass@rabbit-srv:5671/cinemax"
  RABBITMQ_EXPIRATION_URL: "amqps://expiration-user:change-me-expiration-pass@rabbit-srv:5671/cinemax"
  RABBITMQ_MANAGEMENT_USERNAME: "app-user"
  RABBITMQ_MANAGEMENT_PASSWORD: "change-me-strong-pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-ca-cert
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_YOUR_RABBITMQ_CA_CERTIFICATE
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-server-tls
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_YOUR_RABBITMQ_SERVER_CERTIFICATE
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_WITH_YOUR_RABBITMQ_SERVER_PRIVATE_KEY
    -----END PRIVATE KEY-----
